# Multi stage Docker build

# The first stage uses golang:1.19-alpine as build
# The AS keywords names the current build as "build", to be referenced later in the second stage

FROM docker.io/library/golang:1.19-alpine AS build

WORKDIR /home

COPY ./pkg .

RUN go mod download

EXPOSE 8080

# The Second stage uses its base as alpine:latest
# All the steps from the first build  are discarded, and only necessary  artifacts are copied in this stage
# When required

FROM docker.io/library/alpine:latest

WORKDIR /root

# COPY copies the artifacts from the ealier "build" stage to relevant directories of this build process
COPY --from=build /home/library /root/
COPY --from=build /home/main.go /root/
COPY --from=build /home/image /root/image
COPY --from=build /home/templates/. /root/templates

ENTRYPOINT ["./library"]