apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
- ../../base
- qa-ns.yaml


commonLabels:
  env: qa

# Kustomization patches replicas to four in qa namespace 
replicas:
  - name: nginx-test
    count: 4

# This JSON6902 Patch, adds 32000 as nodePort to the Service in the qa namespace
patches:
  - patch: |-
     - op: add
       path: "/spec/ports/0/nodePort"
       value: 32000
    target:
      kind: Service


# This JSON6902 patch pulls a distinct image for qa env from public docker registry
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: santoshdts/nginx:qa
    target:
      kind: Deployment
      