# NOTE:
# To enable this Kustomization to take effect and inflate the included Helm Chart.
# We need to provide a flag `--enable-helm`. 
# This would help Kustomize identify the HelmChart and inflate the Chart accordingly.


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: intelops-

commonLabels:
  env: testing

resources: 
- namespace.yaml

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts 
#  We can use the repo url as well to pull charts from public chart repos. Once, used, it downloads
#  the chart in to local filesystem. 
  version: 23.1.0  # Version of the chart to be installed
  namespace: monitoring
  releaseName: prometheus-helm # Release of the chart.
  includeCRDs: true  # Enable Kustomize to inflate any CRDs in the chart

#  valuesFile: Optional, providing pathto values file, by default uses values.yaml of the chart.
#  additionalValuesFiles: Oprional, enables to provide additional local values file 
#  valuesInline: Optional, we can provide inline values to override native chart values.




