apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cue-deploy
  name: cue-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cue-deploy

  strategy: {}
  template:
    metadata:
      labels:
        app: cue-deploy
  
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}

