
name: Push to GHCR and Sign Container Image

on:
  push:
    branches:
      - '*'

jobs:
  build:
    env:
      IMAGE: ghcr.io/santosh1176/appstek-assignments
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${BRANCH}-${REVISION}"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v1.13.1'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: push-step
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest

      - name: Sign the container image
        run: cosign sign ${{ env.IMAGE }}@${{ steps.push-step.outputs.digest }}




































# name: Docker Build, Push

# on:
#   push:
#     branches:
#       - '*'
#     tags-ignore:
#       - 'release/*'

# jobs:
#   ghcr:
#     env:
#       REGISTRY: ghcr.io
#       IMAGE: santosh1176/appstek-assignments
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#       id-token: write
#     steps:
#       - name: Prepare
#         id: prep
#         run: REVISION=${GITHUB_SHA::8}

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ github.actor }}
#           password: ${{ secrets.GHCR_PAT }}

#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.prep.outputs.REVISION }}
      
      
#       - name: Install cosign
#         uses: sigstore/cosign-installer@main


#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}

#       - name: Sign image with a key
#         run: |
#           cosign sign --key env://COSIGN_PRIVATE_KEY ${TAGS} --yes
#         env:
#           TAGS: ${{env.IMAGE}}@${{ steps.docker_build.outputs.digest }}
#           COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
#           COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
    