apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-build-push-run
spec:
  pipelineRef:
    name: buildah-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: dockerconfig-secret
  params:
  - name: repo-url
    value: https://github.com/santosh1176/appstek-assignments.git
  - name: image-reference
    value: ghcr.io/santosh1176/appstek-assignments/tekton-library:latest