apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: buildah-build-my-repo
spec:
  taskRef:
    name: librarybuildah
  params:
  - name: IMAGE
    value: ghcr.io/santosh1176/appstek-assignments/tekton-buildah:latest
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: my-source